[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D MW_REGION_US915
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  h2zero/NimBLE-Arduino@^1.4.3
  bblanchon/ArduinoJson@^7.3.0
check_tool = cppcheck
check_flags =
  cppcheck: --enable=warning,performance,portability
