include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_final_locals: true
    sort_child_properties_last: true
    unnecessary_lambdas: true
